### ISSUE TITLE
A quickstart script to help newbie try erda without dizzy

### ISSUE THREAD

**Issue by Effet** [erda-project/erda#230]
#### What would you like to be added:
a docker-compose.yml file that let users to run erda in their own computer.

#### Why is this needed:
everyone can have a try of our product, with no dizzy~

- [x] one compose file to run in local #222 
- [x] a more closed uc replacement #224 
- [x] domainless startup #225 
- [x] migration of db #235
